### ISSUE TITLE
Rotary CLI

### ISSUE THREAD

**Issue by jmtsuji** [rotary-genomics/rotary#23]
Thoughts about a CLI for rotary:

- It would be nice to expose the main workflow as well as several of the key utilities built into rotary, so that the utilities can be run in a standalone way if desired (see #21 )
- Example modules that could be available within rotary:
  - `rotary workflow`: complete QC, assembly, polishing, and annotation workflow
    - kind of like `atlas run`. I wonder if we can skip a separate `rotary config` step (to generate a config file) and can just provide all the details needed for the workflow as flags to this module. The `workflow` module would then create a snakemake-readable config and run the config. This would work well with the current model of rotary, where each rotary run is for a single sample (genome). Rotary could be easily run in a `for` loop or via GNU parallel with flags if a user wanted to analyze many samples at the same time...
  - `rotary repair`: fixes the ends of circular contigs
  - `rotary rotate`: rotates circular contigs (e.g., to the midpoint) - helpful for polishing steps
  - `rotary align_start`: finds the _dnaA_ gene and rotates circular contigs to start there; for circular contigs without _dnaA_, rotate them so that no ORFs get interrupted by the contig end (like `circlator fixstart`)
  - `rotary test`: runs test code to make sure rotary is working
  
The `rotary repair` module should be easy, because it is already its own script. Code for `rotary rotate` is already inside the `rotary repair` script and could be made into a standalone script. Code for `rotary align_start` is currently part of the snakefile and might need to be moved into a separate Python script.

**Comment by jmtsuji** [comment]
@leebergstrand

**Comment by LeeBergstrand** [comment]
@jmtsuji I would like something like ATLAS INIT where we can set up a config file and a sample file etc. Would something like that work for you?

**Comment by jmtsuji** [comment]
> @jmtsuji I would like something like ATLAS INIT where we can set up a config file and a sample file etc. Would something like that work for you?

Still thinking about this. I feel like being able to run rotary in a single command (with no need for a separate `init` step) is probably simpler for new users. The `init` then `run` workflow is probably easier for more advanced users who want to run large batches of samples at one time.

Would there be any disadvantages to having a single run command (no `init`) and locking rotary to one sample at a time, but using GNU parallel to automate running a catalog of genomes?

We could still output the config file as one of the outputs of the run, and the CLI could include a `--continue` flag (like is available in SPAdes) so that users can use the config to re-start a failed run partway through.

What are your thoughts? Thanks.

**Comment by LeeBergstrand** [comment]
@jmtsuji So I like doing the batch processing in Snakemake because it loads balances. Once you specify the proper number of CPUs and RAM for each rule, Snakemake will only use the required resources to apply that rule. For example, if you have one rule that needs four threads and another, that takes 8 (see: https://github.com/metagenome-atlas/atlas/blob/c7caea9c198c60f39d250ae35854ca5e0df96245/workflow/rules/binning.smk#L25). Many bioinformatics programs have diminishing returns if you specify too many threads. For example, HMMER plateaus its performance around eight threads (unless you run on a RAM disk). If you have more cores than the number of threads needed for a job and run multiple genomes simultaneously, the load balancer will slot jobs into processing holes. For example, it can assemble one genome while annotating another with HMMER. You don't get into situations where, for example, you are unzipping six genomes simultaneously on one thread each while you have 12 cores. If you used GNU parallel, you could run the risk of either the jobs destroying each other by taking up too much RAM or using a small amount of resources at once.

**Comment by LeeBergstrand** [comment]
> I am still thinking about this. I feel like being able to run rotary in a single command (with no need for a separate `init` step) is probably more straightforward for new users. The `init` then `run` workflow is probably easier for more advanced users who want to run large batches of samples simultaneously.

These things don't need to be mutually exclusive. You could have both. I'm thinking about doing the following:

```rotary run --short_r1 blam_R1.fastq.gz --short_r2 blam_R2.fastq.gz --nano blam.fastq.gz --databases ./databases --out ./out_dir --config ./config.yml``` 

So the ```run``` command would make an ```out_dir``` directory, then put the ```config.yml``` in that directory and make a ``` sample. tsv``` file with the paths to the input files and put that in the directory.

Removing the sample paths from the config and moving them to a separate file is essential from a separation of concerns (https://en.wikipedia.org/wiki/Separation_of_concerns) standpoint. That way, you can transfer the configs between machines or between lab groups or members without digging into them to rename the input file paths.

You could also still have:

```rotary init --path/to/fastq_folder```

This would make the ``` sample.tsv``` file upfront and add a generic config file.

You could just make the ```--short_r1```,  ```--short_r2 ```,  and ```--nano``` flags as optional. If they are not specified, then rotary looks for the ``` sample.tsv``` file and processes using that.

**Comment by LeeBergstrand** [comment]
@jmtsuji What are your thoughts? Thanks.

**Comment by jmtsuji** [comment]
@LeeBergstrand I like your proposed approach!

- Agreed that the load balancing within snakemake is a big plus for being able to run multiple samples in the same run
- I also agree with your proposal to separate the config and sample files
- The CLI examples you gave are nice -- sounds like it will keep rotary intuitive for entry users (or users who only need to run 1 sample) while also exposing the ability to run multiple samples

Shall we go with this approach? Thanks.

**Comment by LeeBergstrand** [comment]
Shall we go with this approach? Thanks. --> let's do this.
