### ISSUE TITLE
Create Rotary Download CLI Command

### ISSUE THREAD

**Issue by LeeBergstrand** [rotary-genomics/rotary#45]
Yeah, that would make sense to add a `rotary download` command eventually. I think this should be pretty straightforward:
- All commands that involve DB downloads are summarized at the top of the snakefile at the moment.
- An additional checkpoint-like rule (e.g., `rule download`) could be added to summarize the outputs from these rules. 
- Then, it would be easy to call this `download` rule via snakemake using the `--until` flag, with very similar code as would be used in `rotary run`.

_Originally posted by @jmtsuji in https://github.com/jmtsuji/rotary/issues/39#issuecomment-1765922554_

**Comment by jmtsuji** [comment]
@LeeBergstrand Check this out: https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html

> Conda deployment also works well for offline or air-gapped environments. Running snakemake --use-conda --conda-create-envs-only will only install the required conda environments without running the full workflow. Subsequent runs with --use-conda will make use of the local environments without requiring internet access.

We could potentially add `snakemake --use-conda --conda-create-envs-only` as part of the download CLI so that all conda envs are also set up using this command. Thoughts?

**Comment by LeeBergstrand** [comment]
@jmtsuji This sounds great. We could add this to the downloads sub-command. However, we should check to see if we need to have the input pipeline files set up beforehand.

**Comment by jmtsuji** [comment]
@LeeBergstrand Good point -- if the input pipeline files are needed, then this flag might not be as useful for our case. I suppose we could try to force it to work by providing end-to-end test files or something. Let's see what the behaviour is like when we have a chance to test it.

**Comment by LeeBergstrand** [comment]
Further Discussed in https://github.com/rotary-genomics/rotary/pull/114#issuecomment-1936528046

> From a maintenance standpoint, it makes more sense to me to have the database download rules in the same snakemake file as the rule that uses the data. That way, if you need to update anything, such as database versions, everything is self-contained in the same place so that you can edit both rules simultaneously. For example, when you specify a new model version name in the download rule and that same model version name in the processing rule, you can add both as a variable at the top of the file. Also, if you need to port things between software programs, everything is in one package. You can copy the file over. I would still add a download.smk file with the rule rule download but it would be the only thing in that file. This rule would be pretty long because it would check for the output files of all the download rules in the other files. Perhaps you could also have sub-rules (e.g., qc_download) in download.smk that check individual download steps and checkpoints). Because of how Snakemake works, you don't need to have all the download rules in download.smk. You could either import download.smk into rotary.smk and call the rule out of rotary.smk or you could import all the other rules into 'download.smk' and call download.smk

**Comment by jmtsuji** [comment]
@LeeBergstrand Thanks for the explanation -- I agree with you that it's better to leave the download rules in the snakefiles where their outputs are used. We can test out adding a `download.smk` file that summarizes the outputs of download rules in the future. Agreed that it could be nice to make sub-rules for downloads, like you mentioned!

**Comment by LeeBergstrand** [comment]
Complete in https://github.com/rotary-genomics/rotary/pull/175
