### ISSUE TITLE
Update readme to reflect new CLI and install.

### ISSUE THREAD

**Issue by LeeBergstrand** [rotary-genomics/rotary#49]
I think the README can be further updated in future before pushing to master and does not need to be fully updated before this PR is merged to develop.

_Originally posted by @jmtsuji in https://github.com/jmtsuji/rotary/pull/46#discussion_r1363278230_

**Comment by jmtsuji** [comment]
Addressed in #127 and elsewhere - although I think we can continue to improve the docs in the future
