### ISSUE TITLE
Update dependancy versions

### ISSUE THREAD

**Issue by LeeBergstrand** [rotary-genomics/rotary#50]
We should probably bump the versions of these dependencies before pushing to master in future (e.g., pandas could now be bumped to pandas 2)

_Originally posted by @jmtsuji in https://github.com/jmtsuji/rotary/pull/46#discussion_r1363283708_

**Comment by LeeBergstrand** [comment]
I have update a few dependancy versions recently.

**Comment by jmtsuji** [comment]
@LeeBergstrand Thanks!
