### ISSUE TITLE
Allow for mixture of samples with or without short-read data.

### ISSUE THREAD

**Issue by LeeBergstrand** [rotary-genomics/rotary#59]
I see -- sounds tricky to modify the logic at the moment. It might work well to revisit having an alternative way to parse the file names (as a low priority feature request) at the same time as changing the code to allow for optional short read data, at some point in the future. Sounds good to set this as a long-term TODO.

_Originally posted by @jmtsuji in https://github.com/jmtsuji/rotary/issues/53#issuecomment-1771928862_

**Comment by jmtsuji** [comment]
@LeeBergstrand I wonder if some of the new semantic helper functions for inputs in snakemake 8 might help with the per-sample switching logic? See https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#the-lookup-function and https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#the-branch-function  For example, using the `lookup` function, we could check if the params for a specific sample show that it is a long-read only sample. Hybrid assembly-specific rules could still be run for the long-read only samples but could have a built-in "bypass" conditional that causes the inputs to be pushed through without changes, if the params show that a sample is long-read only. Alternatively, `branch` could be used to create files for hybrid samples in a special sub-folder that is then subject to hybrid assembly rules. Thoughts? (I am just jotting down some brief notes quickly.)

I hope soon to get back to working on the internal code to replace circlator... this will allow us to upgrade to snakemake 8. We might also be able to temporarily disable circlator on a test branch to try out snakemake 8 before I am finished with the circlator replacement code. Let me know if you think the above semantic helper functions might be of use -- I haven't run any tests yet.

**Comment by jmtsuji** [comment]
@LeeBergstrand I think we decided that, for now, running a mix of samples with hybrid vs. long-read-only datasets is a low priority use case. Users can just run rotary in separate batches of samples with hybrid vs. long read data if needed. Feel free to re-open this issue if you feel it needs to be addressed more urgently.
