### ISSUE TITLE
Integrate repair.py into the rotary CLI

### ISSUE THREAD

**Issue by jmtsuji** [rotary-genomics/rotary#60]
Originally posted by @LeeBergstrand in #47 (with minor edits for clarity):

> @jmtsuji Adding [repair.py] as a sub-command might be tricky as it would require calling repair.py from rotary.py. To support this change, I would likely refactor rotary.py so that the if else block for the subcommands is at the top and the args parsing is in a function for each command. Seems like a lot of work. We would have to do this refactoring to support https://github.com/jmtsuji/rotary/issues/23.

We will need to refactor repair.py to integrate it as a module of rotary, as described in #23

**Comment by LeeBergstrand** [comment]
Will be moved to https://github.com/rotary-genomics/rotary-utils via #152
