### ISSUE TITLE
Refactor aggregate_contigs function in rotary.smk for readability.

### ISSUE THREAD

**Issue by LeeBergstrand** [rotary-genomics/rotary#72]
I already refactored this code a bit by pulling out the path below.

```python
def aggregate_contigs(wildcards):
    # TODO - I do not further use this variable, but checkpoints needs to be called to trigger the checkpoint.
    # Am I doing something wrong?
    checkpoint_output = checkpoints.split_circular_and_linear_contigs.get(**wildcards).output[0]
    circularize_lists_path = f"{wildcards.sample}/circularize/filter/lists"

    return expand("{{sample}}/circularize/combine/{circular_or_linear}.fasta",
                  circular_or_linear=glob_wildcards(os.path.join(circularize_lists_path, "{i}.list")).i)

```

However, the glob wildcards bit should be pulled into its own variable and comments should be added to describe what is going on.

**Comment by LeeBergstrand** [comment]
@jmtsuji When you get a chance, can you refactor this so most of the code isn't being passed directly into the return value? When the paths to the lists were inside the ``` os.path.join```, I had much difficulty finding them when debugging.

**Comment by jmtsuji** [comment]
@LeeBergstrand OK, will take a look.

**Comment by LeeBergstrand** [comment]
Addressed in https://github.com/rotary-genomics/rotary/pull/149
