### ISSUE TITLE
Validate config is up to date when running rotary run.

### ISSUE THREAD

**Issue by LeeBergstrand** [rotary-genomics/rotary#79]
### Problem Description

-  If one updates Rotary and runs it using an existing config file created by a previous version, there may be a situation where either values or names of values in the config have changed. This can cause unexpected errors that will be hard for users to interpret.

### Problem Solution

- We should check that the prior config in the directory does not miss any key values found in the default config stored in the rotary software library.

**Comment by jmtsuji** [comment]
Sounds like a nice idea. For example, we could write a function that reads all the variable names (and maybe their expected types??) in the template config and then compares those variables to the contents of the user-provided config. The function could throw an error or warning if any variables are missing in the user-provided config. This solution would not know which variables are "key" or not, though...

**Comment by LeeBergstrand** [comment]
As discussed above we should add some config validation related to: https://github.com/jmtsuji/rotary/pull/75#discussion_r1391317427

**Comment by LeeBergstrand** [comment]
Addressed by https://github.com/rotary-genomics/rotary/commit/a03ddae8f54b7184abdde34573ac9736726b5171 and https://github.com/rotary-genomics/pungi/commit/34654fccb6278a753a2d650b8a666a83432cc760

The config is compared to the default config (provided as a path), and the code checks if the keys are missing from the config that are present in the default config.

**Comment by jmtsuji** [comment]
Great!
