### ISSUE TITLE
Split rotary snakefile into multiple files

### ISSUE THREAD

**Issue by jmtsuji** [rotary-genomics/rotary#90]
To make rotary's code more understandable, we should split the current `rotary.smk` into multiple snakefiles, for example:

- main: `rotary.smk`
- download: `download.smk` (with DB versions)
- long read qc: `qc_long.smk`
- short read qc: `qc_short.smk`
- assembly: `assembly.smk`
- polishing: `polish.smk`
- circularization: `circularize.smk`
- annotation: `annotate.smk`

**Comment by jmtsuji** [comment]
@LeeBergstrand Are you okay to do this after we merge the current develop into master?

**Comment by LeeBergstrand** [comment]
@jmtsuji Sure!

**Comment by jmtsuji** [comment]
Addressed in #114 (for some reason, linking the PR to the issue doesn't seem to be closing the issue automatically once the PR is merged)
