### ISSUE TITLE
Report read QC stats

### ISSUE THREAD

**Issue by jmtsuji** [rotary-genomics/rotary#91]
Make a rule that runs a QC program (e.g., FastQC) on raw reads and after each QC step. A separate rule might be needed for long vs. short reads if the required stats differ.

In addition, make a summary rule that integrates the QC stats from each individual QC rule into a single summary file. I imagine we should make a separate summary file for long reads vs. short reads.

**Comment by LeeBergstrand** [comment]
@jmtsuji As discussed in https://github.com/rotary-genomics/rotary/issues/92#issuecomment-1858534761, we may want to also compile a bunch of the rule monitoring files (e.g.,  {sample}_repaired_info.tsv, {sample}_circular_info.tsv) into larger TSVs so we can delete entire folders for some steps.

**Comment by LeeBergstrand** [comment]
@jmtsuji What were you thinking of for the summary file? Like a TSV file? I have used https://multiqc.info for some summaries, but given the number of QC steps, it might get confusing.

**Comment by jmtsuji** [comment]
@LeeBergstrand To start, I was thinking that TSV files (e.g., one for each major bullet point above) might be the most straightforward way to summarize the results from the different analysis steps. In the longer term, we could consider making HTML reports with embedded tables and/or plots to summarize the rotary results (e.g., using info from the TSV files), if it's not too difficult to do this. I personally am happy with TSV files, but I wonder if users of the published version of the tool might appreciate a slightly more polished HTML report... what are your thoughts?

I wasn't thinking about MultiQC plots originally, but I'd be open to adding these reports if you think they will be helpful. (I generally assume that the short read data we receive from our sequencing centres are high quality, especially after they have gone through the QC module. Because of this, I normally just check how many reads were removed during QC to confirm that the reads are OK, rather than checking per-base quality metrics in more detailed QC reports. However, I can imagine that the situation of other users could be different.) Are you interested in having this feature as a part of rotary? If so, we might be able to just generate MultiQC reports for the final QC'ed reads at the end of the QC module, rather than after each analysis step. This could be one way to reduce the number of reports generated.

**Comment by jmtsuji** [comment]
@LeeBergstrand I think my opinion has changed a little bit since I first posted this issue. Personally, I'd be happy with just collecting basic stats for the reads after each QC step -- e.g., determining the total number of reads remaining and the average read length. These basic stats could then be compiled into a TSV file at the end of the QC module (e.g., one TSV file for short reads and one TSV file for long reads). I think BBMap, and probably several other basic read manipulation tools, can collect such basic read stats. What do you think about this approach?

I'd be open to running MultiQC, too. It might simplify things to just run MultiQC on the final reads at the end of the QC module. On the other hand, I wonder if MultiQC is needed, given that we will already be running several other read QC tools beforehand that should clean up the reads. Do you think the TSV file(s) described above would be sufficient for most use cases (and users who want to know stats more could run MultiQC themselves)? Or better to include MultiQC? Let me know your thoughts -- thanks.

**Comment by jmtsuji** [comment]
P.S. Related to #157

**Comment by LeeBergstrand** [comment]
> @LeeBergstrand I think my opinion has changed a little bit since I first posted this issue. Personally, I'd be happy with just collecting basic stats for the reads after each QC step -- e.g., determining the total number of reads remaining and the average read length. These basic stats could then be compiled into a TSV file at the end of the QC module (e.g., one TSV file for short reads and one TSV file for long reads). I think BBMap, and probably several other basic read manipulation tools, can collect such basic read stats. What do you think about this approach?
> 
> I'd be open to running MultiQC, too. It might simplify things to just run MultiQC on the final reads at the end of the QC module. On the other hand, I wonder if MultiQC is needed, given that we will already be running several other read QC tools beforehand that should clean up the reads. Do you think the TSV file(s) described above would be sufficient for most use cases (and users who want to know stats more could run MultiQC themselves)? Or better to include MultiQC? Let me know your thoughts -- thanks.

**MultiQC is aggregator.** It takes several FASTQC outputs and combines their plots. So, if one FASTQC report HTML file (I think FASTQC makes both visual charts and TSV data) has a line chart showing how the quality of the reads in a single FASTQ file decreases over read length, then a MULTIQC report would plot several lines, one for each FASTQC result used as input. 

Workflow:

```
FASTQ1 --> FASTQC1 ->\
                       --> MULTIQC1 (Summary Report)
FASTQ2 --> FASTQC2 ->/ 
```

I mostly use MULTIQC to aggregate QC results across samples. For example, in my 16S pipeline, I run FASTQC on multiple sample FASTQ files before and after trimming and then run MULTIQC on these results to make two multi-sample summary reports for before and after QC.

@jmtsuji Questions:

1. Would aggregating charts for each stage of the QC and putting them all on the same line plots make any sense to you?
2. Would aggregating charts across samples make any sense to you?

You can also use MULTIQC to aggregate [QUAST](https://github.com/ablab/quast) reports from several assemblies.

**Comment by LeeBergstrand** [comment]
> I think my opinion has changed a little bit since I first posted this issue. Personally, I'd be happy with just collecting basic stats for the reads after each QC step -- e.g., determining the total number of reads remaining and the average read length. These basic stats could then be compiled into a TSV file at the end of the QC module (e.g., one TSV file for short reads and one TSV file for long reads). I think BBMap, and probably several other basic read manipulation tools, can collect such basic read stats. What do you think about this approach?

@jmtsuji I'll look into this. What info do we need from FASTQC? or do you want to skip the whole FASTQC idea altogether? It provides much more data than what you describe in the TSV above.

Can you run through this workflow below and tell me what stats you like and dislike? Should we run this workflow before and after QC is complete and aggregate across samples? What are your thoughts?

```
FASTQ1 --> FASTQC1 ->\
                       --> MULTIQC1 (Summary Report)
FASTQ2 --> FASTQC2 ->/ 
```

**Comment by LeeBergstrand** [comment]
@jmtsuji Some of my initial code for this is in Draft Pull Request: https://github.com/rotary-genomics/rotary/pull/161

**Comment by jmtsuji** [comment]
> MultiQC is aggregator. It takes several FASTQC outputs and combines their plots. So, if one FASTQC report HTML file (I think FASTQC makes both visual charts and TSV data) has a line chart showing how the quality of the reads in a single FASTQ file decreases over read length, then a MULTIQC report would plot several lines, one for each FASTQC result used as input.

@LeeBergstrand Ah, neat! I hadn't realized how generalizable use of MultiQC was (just took a look at the website). This tool looks handy as a general-purpose aggregator. Thanks for the clarification.

**Comment by jmtsuji** [comment]
Will take a look closer at this (e.g., FastQC outputs) and get back to you soon. Thanks for the draft PR!

**Comment by jmtsuji** [comment]
@LeeBergstrand Finally had the chance to take a look at this. I ran the code in #161 on a test sample and then ran MultiQC on the FastQC outputs. I quite like the HTML summary report from MultiQC! Seems quite informative and helpful. MultiQC also outputs TSV summaries of general read stats, which is great.

The only thing I noticed that seemed to be missing was that the average quality score of the reads was not reported in the TSV summary, although it was reported in the HTML file. I'd be willing to live with this for now.

I think it would be reasonable to include all intermediate QC steps in the MultiQC summary, not just the raw and final reads. I tried making a MultiQC summary using all of the intermediate files in #161, and it still seemed quite readable. We might need to put some kind of number prefix in front of the QC steps so they are sorted in a logical order in the MultiQC plot. Also, we would need to make a separate report for short and long reads, because these often didn't summarize well in a single plot.

Overall, I'd be OK to move forward with making MultiQC summary plots based on FastQC outputs. @LeeBergstrand are you also in favour? I'll leave more specific code comments in #161 . Thanks again for getting started with QC reporting.

**Comment by LeeBergstrand** [comment]
> @LeeBergstrand Finally had the chance to take a look at this. I ran the code in #161 on a test sample and then ran MultiQC on the FastQC outputs. I quite like the HTML summary report from MultiQC! Seems quite informative and helpful. MultiQC also outputs TSV summaries of general read stats, which is great.
> 
> The only thing I noticed that seemed to be missing was that the average quality score of the reads was not reported in the TSV summary, although it was reported in the HTML file. I'd be willing to live with this for now.
> 
> I think it would be reasonable to include all intermediate QC steps in the MultiQC summary, not just the raw and final reads. I tried making a MultiQC summary using all of the intermediate files in #161, and it still seemed quite readable. We might need to put some kind of number prefix in front of the QC steps so they are sorted in a logical order in the MultiQC plot. Also, we would need to make a separate report for short and long reads, because these often didn't summarize well in a single plot.
> 
> Overall, I'd be OK to move forward with making MultiQC summary plots based on FastQC outputs. @LeeBergstrand are you also in favour? I'll leave more specific code comments in #161 . Thanks again for getting started with QC reporting.

@jmtsuji Sounds good I will pursue this.

**Comment by jmtsuji** [comment]
@LeeBergstrand Great!

**Comment by LeeBergstrand** [comment]
Addressed by https://github.com/rotary-genomics/rotary/pull/161
